#!/bin/bash -e

clear && cd ~

sudo apk cache
sudo apk update
sudo apk upgrade
sudo apk add build-base busybox fakeroot
sudo apk add syslinux xorriso squashfs-tools git
sudo apk add alpine-sdk apk-tools alpine-conf
sudo apk add mtools dosfstools grub grub-efi

USER=$(whoami)

if ! sudo groups | grep -q abuild; then
   sudo addgroup abuild
fi

if ! sudo groups $USER | grep -q abuild; then
   sudo usermod -a -G abuild $USER
fi

if [[ ! -d ~/.abuild ]]; then
   echo -en '\n' | abuild-keygen -i -a
fi

if [[ ! -d ~/aports ]]; then
   git clone --single-branch -b master https://gitlab.alpinelinux.org/alpine/aports.git
else
   cd ~/aports
   git pull
   cd ..
fi

cat << EOF > ~/aports/scripts/mkimg.custom.sh
profile_custom() {

   output_format='iso'
   image_ext='iso'
   arch='x86_64'
	hostname='alpine'

   syslinux_serial="0 115200"

   kernel_flavors='lts'
   kernel_addons='zfs'

   kernel_cmdline="unionfs_size=512M console=tty0 console=ttyS0,115200"

	initfs_cmdline='modules=loop,squashfs,sd-mod,usb-storage quiet'

	initfs_features='ata base bootchart nvme ext4 mmc raid scsi squashfs usb'

	modloop_sign=yes

	grub_mod='all_video disk part_gpt part_msdos linux normal configfile efi_gop fat'

   boot_addons='amd-ucode intel-ucode'

   initrd_ucode='/boot/amd-ucode.img /boot/intel-ucode.img'

   apkovl='./aports/scripts/genapkovl.sh'

   apks="\$apks
         kbd-bkeymaps haveged
         mkinitfs syslinux util-linux
         efibootmgr os-prober grub grub-efi
         dhcpcd network-extras tzdata
         openntpd openssl ca-certificates
         coreutils usbutils ethtool hwids
         sudo doas nano
         iptables iptables-openrc
         wireless-tools wpa_supplicant wpa_supplicant-openrc
         iwd iwd-openrc
         curl rsync rsync-openrc wget
         e2fsprogs e2fsprogs-extra dosfstools mtools lvm2
         nfs-utils ntfs-3g btrfs-progs xfsprogs f2fs-tools
         zfs-lts zfs-openrc zfs-scripts zfs-utils-py
         parted sfdisk sgdisk
         "

}
EOF

chmod +x ~/aports/scripts/mkimg.custom.sh

if [[ -d ~/alpine ]]; then
   sudo rm -r ~/alpine
fi

sh ~/aports/scripts/mkimage.sh \
--profile custom \
--arch x86_64 \
--outdir ~/ \
--workdir ~/alpine \
--repository https://dl-cdn.alpinelinux.org/alpine/edge/main \
--repository https://dl-cdn.alpinelinux.org/alpine/edge/community

#end
