#!/bin/bash -e

clear && cd ~

sudo apk update
sudo apk upgrade
sudo apk add build-base busybox fakeroot
sudo apk add syslinux xorriso squashfs-tools git
sudo apk add alpine-sdk apk-tools alpine-conf
sudo apk add mtools dosfstools grub grub-efi

USER=$(whoami)

if ! sudo groups | grep -q abuild; then
   sudo addgroup abuild
fi

if ! sudo groups $USER | grep -q abuild; then
   sudo usermod -a -G abuild $USER
fi

if [[ ! -d ~/.abuild ]]; then
   echo -en '\n' | abuild-keygen -i -a
fi

if [[ ! -d ~/aports ]]; then
   git clone --single-branch -b master https://gitlab.alpinelinux.org/alpine/aports.git
else
   cd ~/aports
   git pull
   cd ..
fi

cd ~/aports/scripts/
curl -LO raw.githubusercontent.com/0free/AlpineLinux/1/apkovl.sh
cd ~

cat << EOF > ~/aports/scripts/mkimg.linux.sh
profile_linux() {

   output_format='iso'
   image_ext='iso'
   arch='x86_64'
	hostname='alpine'

	initfs_cmdline='modules=loop,squashfs,sd-mod,usb-storage quiet'

	initfs_features='base nvme ata usb bootchart btrfs zfs xfs ext4 f2fs lvm mmc raid scsi squashfs'

	modloop_sign=yes

	grub_mod='all_video disk part_gpt part_msdos linux normal configfile efi_gop fat'

   boot_addons='amd-ucode intel-ucode'

   initrd_ucode='/boot/amd-ucode.img /boot/intel-ucode.img'

   apkovl='./aports/scripts/apkovl.sh'

   kernel_flavors='lts'
   kernel_addons='xtables-addons'

   apks="\$apks
         alpine-base busybox kbd-bkeymaps
         dhcpcd haveged tzdata
         linux-firmware-other
         linux-firmware-amd linux-firmware-amd-ucode
         linux-firmware-amdgpu linux-firmware-radeon
         linux-firmware-nvidia
         linux-firmware-intel linux-firmware-i915
         linux-firmware-rtl_bt linux-firmware-rtl_nic
         linux-firmware-rtlwifi
         linux-firmware-brcm
         linux-firmware-qca
         syslinux efibootmgr os-prober grub grub-efi
         util-linux coreutils usbutils ethtool
         bash bash-completion sudo doas nano
         openssl curl wget rsync
         network-extras iwd dbus
         e2fsprogs e2fsprogs-extra dosfstools mtools lvm2
         btrfs-progs xfsprogs nfs-utils ntfs-3g f2fs-tools
         sfdisk sgdisk
         zfs
        "

}
EOF

chmod +x ~/aports/scripts/mkimg.linux.sh

sed -i 's|discover_retries = 5|discover_retries = 0|g' ~/aports/main/busybox/0005-udhcpc-set-default-discover-retries-to-5.patch

sh ~/aports/scripts/mkimage.sh \
--profile linux \
--arch x86_64 \
--outdir ~/ \
--workdir ~/alpine \
--repository https://dl-cdn.alpinelinux.org/alpine/edge/main \
--repository https://dl-cdn.alpinelinux.org/alpine/edge/community \
--repository https://dl-cdn.alpinelinux.org/alpine/edge/testing

#end
